### ISSUE TITLE
Filtered posts take up too much space

### ISSUE THREAD

**Issue by vmstan** [mastodon/mastodon-ios#441]
When posts in the timeline are filtered, they take up too much visual space in the app. The website collapses them down to a single line entry, but in the app it's almost not worth the filter especially with a large post, as it's jumping out that something is missing when it takes up 75% of the visual space.

Example
![IMG_3604](https://user-images.githubusercontent.com/3002053/170316563-2027cae4-219a-42bb-a305-e6fe8362d2fe.PNG)

**Comment by MainasuK** [comment]
The filter works in local to make the content hidden right now and it's working alongside the timeline display workflow. At that point the cell height is fixed. Maybe I cloud improve it by make the filter as a part of content fill procession or using preload method to check the filter or not. 

And thank your for your feedback.

**Comment by vmstan** [comment]
I also noticed that if I have "Drop instead of hide" selected from the web interface, this isn't respected in the app. Not being familiar with the API, is that not a setting passed to clients?

And not to put too fine a point on it, but this one really made me chuckle.

![IMG_3624](https://user-images.githubusercontent.com/3002053/170513523-ad609d87-0e9f-45b7-9553-36d03e93bd3e.PNG)

**Comment by haugenhus** [comment]
To add to this (feature)(suggestion) I would like to see the avatar and name of the account responsible for the filtered post, as well as the meatball menu to be able to mute them.

While it is not appropriate to block or report an account without actually looking at the content, if an account is always showing up in my feed as filtered I may simply want to mute them so that my feed isn't cluttered with filter warnings.

**Comment by nlmunro** [comment]
On an iPad with multiple filtered items, it keeps your fingers busy swiping down!

**Comment by TS6ix2GaH3q679h5** [comment]
I mentioned this in another thread but yes, I'm facing this issue too. Multiple things are filtered (which is good!) but the resulting display is not.

My settings page looks like:

> **Chose which action to perform when a post matches the filter**
> Hide with a warning
> _Hide the filtered content behind a warning mentioning the filter's title_
> Hide completely
> _Completely hide the filtered content, behaving as if it did not exist_

This does not look as though they completely do not exist:

<img width="375" alt="image" src="https://github.com/user-attachments/assets/d66ef0df-b6c0-4c9b-87df-0207e487d192">

On the web version, these posts are completely removed and virtually non-existent (good!). In my third party Mastodon client app, same (good!). 

But in the official iOS app, I get the behavior as shown above.

**Comment by thomas-shirley** [comment]
It's been a while since this report was opened and it really does impact the experience when you encounter multiple filtered items.

Here are some examples of how other apps handle filters:

**Ice Cubes**:
![Image](https://github.com/user-attachments/assets/983659d0-7282-4a45-9958-d608a9b868af)
 - Totally minimises post
 - Hides retooter username
 - Hides original tooter user name
 - Displays applied filter

**Mammoth**:
![Image](https://github.com/user-attachments/assets/b82d8416-c15f-4181-83cd-0d8acbadaf0a)
 - Keeps text area a reasonable size
 - Shows original tooter username
 - Shows retooter username
 - Displays applied filter

Personally, I prefer the approach taken by Mammoth. Being able to see the contextual metadata is better for understanding who is being filtered.

**Comment by whattherestimefor** [comment]
This was improved, see https://github.com/mastodon/mastodon-ios/pull/1300#issue-2310235990

The issue will be revisited as we work through improving the post and time line layouts.  Thank you!

**Comment by haugenhus** [comment]
I apologize if I've misunderstood the meaning of marking this issue closed, but While https://github.com/mastodon/mastodon-ios/pull/1300#issue-2310235990 appears to have improved the Content Warning issue, it does not appear to have addressed any part of the Content Filter issues reported here:
- Filtered content still occupies the full space of the unfiltered content
- Filters set to "Hide Completely" are handled the same as those set to "Hide with Warning"
- Filtered content does not display the name of the filter in effect

Though there are ideas in these comments about improving the UX/UI, the three points above represent behaviour inconsistent with what is expected.


The there images below demonstrate the issues noted above.

The filtered post:
![image](https://github.com/user-attachments/assets/97767dfe-3784-4432-85d8-9454dafe03a3)

The filtered post un-hidden: 
![image](https://github.com/user-attachments/assets/4790166f-4681-4920-bb1e-28579fcb74a7)

The filter applied:
![image](https://github.com/user-attachments/assets/b88f89f8-6bb8-4500-b4e2-4fe79c8436ea)

**Comment by vmstan** [comment]
Correct. As the original requester I would submit that this issue is far from done and a major reason why people don't use the official app.

**Comment by renchap** [comment]
@kaleb-haugen this is surprising to me, at least the height issue should have been fixed. Can you check the app version number in Settings => About Mastodon?

**Comment by thomas-shirley** [comment]
Im running iOS v2024.10 (6834) and the filtering height issue is still present.

**Comment by haugenhus** [comment]
I'm on iOS v2024.10 (6834)

**Comment by TS6ix2GaH3q679h5** [comment]
I’m on iOS v2024.10 (6834) and I too am still seeing “full” height filtered items. 

I have to agree with @vmstan that this is a major reason I prefer not to use the official app. It gets so tiring scrolling through pages and pages of meaningless filler space. I use a lot of filters (mostly to remove anything political) and as a result my home timeline in the official app is truly just pages of blank “Filtered” space. In third party apps, that content is 100% hidden and I only see true (unfiltered) posts. 

![Image](https://github.com/user-attachments/assets/4c7bf290-5d8b-450f-8cee-0808e2a49514)

**Comment by rafelangston** [comment]
Mastodon for iOS v2024.10 (6834)

**Comment by vmstan** [comment]
🥳

**Comment by haugenhus** [comment]
❤️

**Comment by brendanjones** [comment]
@whattherestimefor will the fix you made also address https://github.com/mastodon/mastodon-ios/issues/789 ?

**Comment by vmstan** [comment]
At the moment it does not.

**Comment by brendanjones** [comment]
I see that one has since also been addressed 👍

**Comment by TS6ix2GaH3q679h5** [comment]
I can confirm that the overly-lengthy Filtered space is a more manageable size now (see below) on Mastodon iOS 2024.11 (6903):

![Image](https://github.com/user-attachments/assets/54118754-5859-4bc0-907b-7e798a9e499d)

Yet the issue of respecting the **type** of filtering still persists. 

I have this filter set on the server to “completely hide” the content “as if it did not exist”: 

![Image](https://github.com/user-attachments/assets/ea58215c-da0d-4d82-85ae-f3f031504e21)

But this is clearly not happening. The app is simply filtering under the “hide with a warning” type behavior, thus not respecting the choice I set in the home server preferences. This is while browsing my Local timeline, so it certainly ought to be respecting that choice, even if I can understand why it might not respect filtering when browsing a different instance’s timeline.

**Comment by whattherestimefor** [comment]
@TS6ix2GaH3q679h5 Thanks for the report! I've reopened that issue: https://github.com/mastodon/mastodon-ios/issues/1354
