### ISSUE TITLE
[BUG] Audio media posted from web-app not available on iOS app

### ISSUE THREAD

**Issue by crackajack77** [mastodon/mastodon-ios#642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Posting an audio file from web-application won't show up on IOS app, but is playable from web-app. Text will be shown, media not.

See this post for example
https://layer8.space/@pd/109365014849444165

### Steps To Reproduce

1. Post an audio file from web-app, including image artwork.
2. Include Text
3. Open Mastadon iOS App and open your profile
4.

### Environment

```markdown
- Device: iPhone 11
- OS: 14.6
- Version: v1.4.5
- Build: 144
```

**Comment by j-f1** [comment]
This should be fixed by https://github.com/mastodon/mastodon-ios/pull/611!

**Comment by j-f1** [comment]
Actually wound up being fixed by #805

**Comment by FediVideos** [comment]
Still isn't fixed!

I've tried posting an audio file on the web app and the attachment is invisible on the official Masto iOS app. See this post for an example: https://mstdn.social/@feditips/109644044918079289

**Comment by FediVideos** [comment]
Will this fix be in the next update?

Still seeing this problem at the moment (try https://mstdn.social/@feditips/109644044918079289 as an example).

**Comment by j-f1** [comment]
It should be!

**Comment by whattherestimefor** [comment]
Cannot reproduce in 2024.12.
